config/routes.rb
Rails.application.routes.draw do

  resources :asignaciones
  resources :proveedores
  resources :personas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/login', to:'seguridad#login'
  get '/inicio', to:'inicio#casa'
  get '/noacceso', to:'inicio#noacceso'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proveedore.rb
class Proveedore < ApplicationRecord
end

app/controllers/proveedores_controller.rb
class ProveedoresController < BaseController
  before_action :set_proveedore, only: [:show, :edit, :update, :destroy]

  # GET /proveedores
  # GET /proveedores.json
  def index
    @proveedores = Proveedore.all
  end

  # GET /proveedores/1
  # GET /proveedores/1.json
  def show
  end

  # GET /proveedores/new
  def new
    @proveedore = Proveedore.new
  end

  # GET /proveedores/1/edit
  def edit
  end

  # POST /proveedores
  # POST /proveedores.json
  def create
    @proveedore = Proveedore.new(proveedore_params)

    respond_to do |format|
      if @proveedore.save
        format.html { redirect_to @proveedore, notice: 'Proveedor ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @proveedore }
      else
        format.html { render :new }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveedores/1
  # PATCH/PUT /proveedores/1.json
  def update
    respond_to do |format|
      if @proveedore.update(proveedore_params)
        format.html { redirect_to @proveedore, notice: 'Proveedor ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @proveedore }
      else
        format.html { render :edit }
        format.json { render json: @proveedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedores/1
  # DELETE /proveedores/1.json
  def destroy
    @proveedore.destroy
    respond_to do |format|
      format.html { redirect_to proveedores_url, notice: 'Proveedor ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proveedore
      @proveedore = Proveedore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proveedore_params
      params.require(:proveedore).permit(:identificacion, :nombre, :idCiudad, :idDpto, :dirreccion, :correo, :telefonos, :idTipoProv, :idEstadoProv, :idCategoriaProv, :comentario)
    end
end

app/views/proveedores/_form.html.erb
<%= form_with(model: proveedore, local: true) do |form| %>
  <% if proveedore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proveedore.errors.count, "error") %> prohibited this proveedore from being saved:</h2>

      <ul>
      <% proveedore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row col-sm-4">
    <%= form.label :identificacion %>
    <%= form.number_field :identificacion, id: :proveedore_identificacion, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :proveedore_nombre, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idCiudad %>
    <%= form.number_field :idCiudad, id: :proveedore_idCiudad, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idDpto %>
    <%= form.number_field :idDpto, id: :proveedore_idDpto, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :dirreccion %>
    <%= form.text_field :dirreccion, id: :proveedore_dirreccion, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :proveedore_correo, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :telefonos %>
    <%= form.number_field :telefonos, id: :proveedore_telefonos, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idTipoProv %>
    <%= form.number_field :idTipoProv, id: :proveedore_idTipoProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idEstadoProv %>
    <%= form.number_field :idEstadoProv, id: :proveedore_idEstadoProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :idCategoriaProv %>
    <%= form.number_field :idCategoriaProv, id: :proveedore_idCategoriaProv, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :comentario %>
    <%= form.text_field :comentario, id: :proveedore_comentario, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", :class=> "btn btn-secondary" %>
       
  </div>
<% end %>

app/views/proveedores/edit.html.erb
<h1>Editar Proveedores</h1>
<hr class="division">
<%= link_to 'Regresar', proveedores_path, class:"btn btn-info" %>
<%= link_to 'Mostrar', @proveedores, class:"btn btn-warning" %> 

<%= render 'form', proveedore: @proveedore %>

 <% if @operaciones.include?("Eliminar") %>
       <%= link_to 'Eliminar', @proveedore, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %>
   <% end %>

app/views/proveedores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveedores</h1>
<hr class="division">
<%= link_to 'Nuevo', new_proveedore_path, :class=>"btn btn-primary btn-sm" %>
<table class="table table-bordered table-sm">
  <thead>
    <tr>
      <th class="w-50 text-center">Identificacion</th>
      <th class="w-50 text-center">Nombre</th>
      <th class="w-50 text-center">Idciudad</th>
      <th class="w-50 text-center">Iddpto</th>
      <th class="w-50 text-center">Dirreccion</th>
      <th class="w-50 text-center">Correo</th>
      <th class="w-50 text-center">Telefonos</th>
      <th class="w-50 text-center">Idtipoprov</th>
      <th class="w-50 text-center">Idestadoprov</th>
      <th class="w-50 text-center">Idcategoriaprov</th>
      <th class="w-50 text-center">Comentario</th>
    </tr>
  </thead>

  <tbody>
    <% @proveedores.each do |proveedore| %>
      <tr>
        <td><a href="/proveedores/<%= proveedore['id'] %>" "Mostrar"><%= proveedore.identificacion %></a></td>
        <td><%= proveedore.nombre %></td>
        <td><%= proveedore.idCiudad %></td>
        <td><%= proveedore.idDpto %></td>
        <td><%= proveedore.dirreccion %></td>
        <td><%= proveedore.correo %></td>
        <td><%= proveedore.telefonos %></td>
        <td><%= proveedore.idTipoProv %></td>
        <td><%= proveedore.idEstadoProv %></td>
        <td><%= proveedore.idCategoriaProv %></td>
        <td><%= proveedore.comentario %></td>
        <!--<td><%= link_to 'Show', proveedore %></td>
        <td><%= link_to 'Edit', edit_proveedore_path(proveedore) %></td>
        <td><%= link_to 'Destroy', proveedore, method: :delete, data: { confirm: 'Are you sure?' } %>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/proveedores/new.html.erb
<h1>Nuevo Proveedor</h1>
<hr class="division">
<%= link_to 'Regresar', proveedores_path, class:"btn btn-info" %>

<%= render 'form', proveedore: @proveedore %>

app/views/proveedores/show.html.erb
<h4>Informacion de proveedores</h4>
<hr class="division">
<%= link_to 'Regresar', proveedores_path,class:"btn btn-info" %>
<div class="container">
<p id="notice"><%= notice %></p>

<form>
<div class="form-group col-md-4">
  <label>Identificacion:</label>
  <input type="text" class="form-control" value="<%= @proveedore.identificacion %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Nombre:</label>
  <input type="text" class="form-control" value="<%= @proveedore.nombre %>on %>" readonly>
  
</div>

<div class="form-group col-md-4">
 <label>Idciudad:</label>
 <input type="text" class="form-control" value="<%= @proveedore.idCiudad %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Iddpto:</label>
  <input type="text" class="form-control" value="<%= @proveedore.idDpto %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Dirreccion:</label>
  <input type="text" class="form-control" value="<%= @proveedore.dirreccion %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Correo:</label>
  <input type="text" class="form-control" value="<%= @proveedore.correo %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Telefonos:</label>
  <input type="text" class="form-control" value="<%= @proveedore.telefonos %>" readonly>
 
</div>

<div class="form-group col-md-4">
  <label>Idtipoprov:</label>
  <input type="text" class="form-control" value="<%= @proveedore.idTipoProv %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Idestadoprov:</label>
  <input type="text" class="form-control" value="<%= @proveedore.idEstadoProv %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Idcategoriaprov:</label>
  <input type="text" class="form-control" value="<%= @proveedore.idCategoriaProv %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Comentario:</label>
  <input type="text" class="form-control" value="<%= @proveedore.comentario %>" readonly>
  
</div>
</form>

<% if @operaciones.include?("Modificar") %>
  <%= link_to 'Modificar', edit_proveedore_path(@proveedore), class:"btn btn-success" %>
<% end%>

 

</div>