config/routes.rb
Rails.application.routes.draw do

  resources :asignaciones
  resources :proveedores
  resources :personas
  resources :rol_opcion_operaciones
  resources :opciones
  resources :valor_parametros
  resources :usuarios
  root 'seguridad#login'
  resources :parametros
  post '/auth', to:'seguridad#autenticar'
  get '/login', to:'seguridad#login'
  get '/inicio', to:'inicio#casa'
  get '/noacceso', to:'inicio#noacceso'
  get '/logout', to:'seguridad#logout'
  get '/valp/:id', to: "valor_parametros#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/asignacione.rb
class Asignacione < ApplicationRecord
  belongs_to :persona
end

app/controllers/asignaciones_controller.rb
class AsignacionesController < BaseController
  before_action :set_asignacione, only: [:show, :edit, :update, :destroy]

  # GET /asignaciones
  # GET /asignaciones.json
  def index
    @asignaciones = Asignacione.all
  end

  # GET /asignaciones/1
  # GET /asignaciones/1.json
  def show
  end

  # GET /asignaciones/new
  def new
    @asignacione = Asignacione.new
  end

  # GET /asignaciones/1/edit
  def edit
  end

  # POST /asignaciones
  # POST /asignaciones.json
  def create
    @asignacione = Asignacione.new(asignacione_params)

    respond_to do |format|
      if @asignacione.save
        format.html { redirect_to @asignacione, notice: 'Asignacion ha sido creada exitosamente.' }
        format.json { render :show, status: :created, location: @asignacione }
      else
        format.html { render :new }
        format.json { render json: @asignacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaciones/1
  # PATCH/PUT /asignaciones/1.json
  def update
    respond_to do |format|
      if @asignacione.update(asignacione_params)
        format.html { redirect_to @asignacione, notice: 'Asignacion fue modificada exitosamente.' }
        format.json { render :show, status: :ok, location: @asignacione }
      else
        format.html { render :edit }
        format.json { render json: @asignacione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaciones/1
  # DELETE /asignaciones/1.json
  def destroy
    @asignacione.destroy
    respond_to do |format|
      format.html { redirect_to asignaciones_url, notice: 'Asignacion ha sido eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignacione
      @asignacione = Asignacione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignacione_params
      params.require(:asignacione).permit(:persona_id, :fecha, :idEstadoPersonaEquipo, :eliminado)
    end
end

app/views/asignaciones/_form.html.erb
<%= form_with(model: asignacione, local: true) do |form| %>
  <% if asignacione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignacione.errors.count, "error") %> prohibited this asignacione from being saved:</h2>

      <ul>
      <% asignacione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row col-sm-4">
    <%= form.label :persona_id %>
    <%= form.text_field :persona_id, id: :asignacione_persona_id, class:"form-control" %>
  </div>

  <div class="form-group row col-sm-4">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :asignacione_fecha, class:"form-control"  %>
  </div>

  <div class="form-group row col-sm-4 "> 
    <%= form.label :idEstadoPersonaEquipo %>
    <%= form.number_field :idEstadoPersonaEquipo, id: :asignacione_idEstadoPersonaEquipo, class:"form-control" %>
  </div>
<!--
  <div class="form-group row col-sm-4">
    <%= form.label :eliminado %>
    <%= form.number_field :eliminado, id: :asignacione_eliminado, class:"form-control" %>
  </div>
-->
  <div class="actions">
    <%= form.submit "Guardar", :class=>"btn btn-secondary"%>
    <%= link_to 'Eliminar', asignacione, :class => "btn btn-danger", method: :delete, data: { confirm: 'Confirme Eliminación?' } %></td>
  </div>
<% end %>

app/views/asignaciones/edit.html.erb
<h1>Editar Asignaciones</h1>
<hr class="division">
<%= link_to 'Regresar', asignaciones_path, class:"btn btn-info" %>
<%= link_to 'Mostrar', @asignaciones, class:"btn btn-warning" %> 


<%= render 'form', asignacione: @asignacione %>

app/views/asignaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignaciones</h1>
<hr class="division">
<%= link_to 'Nuevo', new_asignacione_path,class:'btn btn-primary btn-sm' %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="w-50 text-center">IdPersona</th>
      <th class="w-50 text-center">Fecha</th>
      <th class="w-50 text-center">Idestadopersonaequipo</th>
      <!-- <th class="w-50 text-center">Eliminado</th> -->
    
    </tr>
  </thead>

  <tbody>
    <% @asignaciones.each do |asignacione| %>
      <tr>
        <td><a href="/asignaciones/<%= asignacione['id'] %>" "Mostrar"><%= asignacione.persona_id %></a></td>
        <td><%= asignacione.fecha %></td>
        <td><%= asignacione.idEstadoPersonaEquipo %></td>
       <!-- <td><%= asignacione.eliminado %></td>
        <td><%= link_to 'Show', asignacione %></td>
        <td><%= link_to 'Edit', edit_asignacione_path(asignacione) %></td>
        <td><%= link_to 'Destroy', asignacione, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/asignaciones/new.html.erb
<h1>Nueva Asignación</h1>
<hr class="division">
<%= link_to 'Regresar', asignaciones_path, class:"btn btn-info" %>

<%= render 'form', asignacione: @asignacione %>

app/views/asignaciones/show.html.erb
<h4>Informacion de Asignaciones</h4>
<hr class="division">
<%= link_to 'Regresar', asignaciones_path, class:"btn btn-info" %>

<div id="notice"><%= notice %></div>
<form>
<div class="form-group col-md-4">
  <label>Persona:</label>
   <input type="text" class="form-control" value="<%= @asignacione.persona_id %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Fecha:</label>
   <input type="text" class="form-control" value="<%= @asignacione.fecha %>" readonly>
  
</div>

<div class="form-group col-md-4">
  <label>Idestadopersonaequipo:</label>
   <input type="text" class="form-control" value=" <%= @asignacione.idEstadoPersonaEquipo %>" readonly>
 
</div>
</form>
<!--
<p>
  <strong>Eliminado:</strong>
  <%= @asignacione.eliminado %>
</p>
-->
<% if @operaciones.include?("Modificar") %>
  <%= link_to 'Modificar', edit_asignacione_path(@asignacione), class:"btn btn-success" %>
<% end%>
 